jobs:
  junit:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout codes
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      name: Test with Maven
      run: mvn clean test -B -U -Psonatype
    strategy:
      matrix:
        java:
        - 8
        - 11
        - 17
        os:
        - windows-latest
        - ubuntu-latest
name: Test with Junit
on:
  repository_dispatch:
    types: trigger-ga___junit_test.yml
