jobs:
  check-license:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout codes
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Check License Header
      uses: apache/skywalking-eyes@v0.4.0
name: License checker
on:
  repository_dispatch:
    types: trigger-ga___license-checker.yml
