jobs:
  check-snapshot:
    outputs:
      IS_SNAPSHOT: ${{ steps.set_output_1.outputs.IS_SNAPSHOT }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout codes
      uses: actions/checkout@v3
    - continue-on-error: true
      id: set_output_1
      name: Check deploy type
      run: "line=\"$(grep SNAPSHOT pom.xml || true)\"\necho $line\nif [ -n \"$line\"\
        \ ]; then\n  echo \"IS_SNAPSHOT=true\" >> $GITHUB_OUTPUT\nelse\n  echo \"\
        IS_SNAPSHOT=false\" >> $GITHUB_OUTPUT\nfi\n"
  snapshot:
    if: ${{ needs.check-snapshot.outputs.IS_SNAPSHOT == 'true' }}
    needs: check-snapshot
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout codes
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'
        server-id: nexus-snapshots
        server-password: MAVEN_PASSWORD
        server-username: MAVEN_USERNAME
    - continue-on-error: true
      env:
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      name: Publish package
      run: mvn clean deploy -B -U -Psonatype
name: Snapshot
on:
  repository_dispatch:
    types: trigger-ga___snapshot.yml
